// Shared job data and assets for the Careers area
export const JOB_LISTINGS = [
  {
    id: 1,
    title: 'Senior Full Stack Engineer',
    location: 'Remote / New York',
    department: 'Engineering',
    type: 'Full-Time',
    seniority: 'Senior',
    salary: '$110k - $160k',
    postedAt: '2025-10-20',
    description:
      'Build and maintain customer-facing web applications. You will design APIs, own features end-to-end, and help mentor junior engineers.',
    responsibilities: [
      'Design, develop and maintain full-stack features',
      'Collaborate with product and design to ship delightful experiences',
      'Mentor junior engineers and conduct code reviews',
    ],
    requirements: [
      '5+ years building web applications',
      'Strong experience with React and Node.js',
      'Experience with SQL and NoSQL databases',
    ],
    niceToHave: ['Experience with TypeScript', 'Familiarity with cloud platforms (AWS/GCP)'],
    perks: ['Flexible hours', 'Health & dental', 'Learning stipend', 'Stock options'],
  },
  {
    id: 2,
    title: 'UX/UI Designer (Mobile Focus)',
    location: 'San Francisco, CA',
    department: 'Design',
    type: 'Full-Time',
    seniority: 'Mid-Senior',
    salary: '$90k - $130k',
    postedAt: '2025-09-12',
    description:
      'Design delightful mobile-first experiences. Work closely with product and engineering to ship polished interfaces.',
    responsibilities: [
      'Create user flows, wireframes and high-fidelity mockups',
      'Conduct user research and usability tests',
      'Collaborate with engineers to ship designs',
    ],
    requirements: ['3+ years in product design', 'Strong portfolio with mobile work', 'Proficiency with Figma or similar'],
    niceToHave: ['Motion design experience', 'Experience with design systems'],
    perks: ['Remote-friendly', 'Conference budget', 'Wellness benefits'],
  },
  {
    id: 3,
    title: 'Digital Marketing Specialist',
    location: 'Remote / London',
    department: 'Marketing',
    type: 'Full-Time',
    seniority: 'Associate',
    salary: '£35k - £50k',
    postedAt: '2025-11-01',
    description:
      'Drive growth through paid and organic channels. You will run campaigns, analyze performance, and optimize funnels to improve acquisition metrics.',
    responsibilities: ['Plan and execute digital campaigns', 'Analyze performance and report insights', 'Work with content and product teams'],
    requirements: ['2+ years in digital marketing', 'Familiar with paid acquisition channels', 'Strong Excel/Sheets skills'],
    niceToHave: ['Experience with marketing automation', 'Basic SQL knowledge'],
    perks: ['Performance bonus', 'Flexible schedule', 'Learning fund'],
  },
  {
    id: 4,
    title: 'Sales Development Representative',
    location: 'New York, NY',
    department: 'Sales',
    type: 'Full-Time',
    seniority: 'Entry',
    salary: '$50k - $70k + commission',
    postedAt: '2025-08-05',
    description: 'Generate leads and qualify prospects for the sales team. Ideal for outgoing candidates who enjoy building relationships.',
    responsibilities: ['Prospect and outreach', 'Qualify leads', 'Work with account executives'],
    requirements: ['Excellent communication skills', 'Comfortable with outreach tools'],
    niceToHave: ['Experience in B2B SaaS sales'],
    perks: ['Commission plan', 'Team outings', 'Health coverage'],
  },
  {
    id: 5,
    title: 'Product Manager, AI Solutions',
    location: 'Remote',
    department: 'Product',
    type: 'Full-Time',
    seniority: 'Senior',
    salary: '$130k - $180k',
    postedAt: '2025-10-02',
    description:
      'Lead product initiatives that leverage AI to solve customer problems. You will work with ML engineers and platform teams to bring models to production.',
    responsibilities: ['Define product strategy', 'Prioritize roadmap', 'Collaborate with ML and engineering teams'],
    requirements: ['3+ years as a PM', 'Experience shipping ML/AI products', 'Strong analytical skills'],
    niceToHave: ['Familiarity with model deployment', 'Experience with data engineering'],
    perks: ['Equity', 'Learning stipend', 'Remote-first culture'],
  },
  // Additional dummy listings (India-focused) for testing and demo
  {
    id: 6,
    title: 'Backend Engineer (Node.js)',
    location: 'Bengaluru, India',
    department: 'Engineering',
    type: 'Full-Time',
    seniority: 'Mid-Senior',
    salary: '₹25L - ₹40L',
    postedAt: '2025-11-05',
    description:
      'Build scalable backend services and APIs used by millions of users. Focus on reliability, performance, and observability.',
    responsibilities: [
      'Design and implement microservices',
      'Improve performance and reliability',
      'Collaborate with frontend and product teams',
    ],
    requirements: ['3+ years with Node.js or similar', 'Experience with PostgreSQL or MongoDB', 'Good understanding of distributed systems'],
    niceToHave: ['Experience with Kubernetes', 'Knowledge of message queues (Kafka, RabbitMQ)'],
    perks: ['Flexible hybrid work', 'Health insurance', 'Learning & conference budget'],
  },
  {
    id: 7,
    title: 'Frontend Engineer (React)',
    location: 'Hyderabad, India',
    department: 'Engineering',
    type: 'Full-Time',
    seniority: 'Mid',
    salary: '₹18L - ₹30L',
    postedAt: '2025-10-28',
    description: 'Create polished, accessible web interfaces and reusable component libraries using React and TypeScript.',
    responsibilities: ['Build responsive UI components', 'Work with designers to implement prototypes', 'Optimize for accessibility and performance'],
    requirements: ['2+ years with React', 'Familiarity with TypeScript', 'Good CSS and layout skills'],
    niceToHave: ['Experience with Next.js', 'Design system experience'],
    perks: ['Stock options', 'Flexible hours', 'Remote-friendly'],
  },
  {
    id: 8,
    title: 'DevOps Engineer',
    location: 'Pune, India',
    department: 'Platform',
    type: 'Full-Time',
    seniority: 'Mid-Senior',
    salary: '₹20L - ₹35L',
    postedAt: '2025-11-07',
    description: 'Improve our CI/CD, infrastructure automation, and cloud costs while ensuring security and observability.',
    responsibilities: ['Maintain CI/CD pipelines', 'Automate infrastructure', 'Monitor and reduce cloud spend'],
    requirements: ['Experience with Terraform or CloudFormation', 'Kubernetes and container experience', 'Scripting skills (Python/Bash)'],
    niceToHave: ['Experience with Prometheus/Grafana', 'Cost optimization experience'],
    perks: ['Training allowance', 'Medical benefits', 'Work-from-home support'],
  },
  {
    id: 9,
    title: 'Business Development Executive',
    location: 'Mumbai, India',
    department: 'Sales',
    type: 'Full-Time',
    seniority: 'Entry',
    salary: '₹6L - ₹10L + commission',
    postedAt: '2025-10-15',
    description: 'Identify prospects, run outreach campaigns, and qualify leads to grow our enterprise pipeline in India.',
    responsibilities: ['Prospect and qualify leads', 'Coordinate demos with AEs', 'Maintain CRM hygiene'],
    requirements: ['Excellent communication skills', 'Comfortable with outreach tools'],
    niceToHave: ['Experience in SaaS sales', 'Familiarity with enterprise procurement'],
    perks: ['Competitive commission', 'Team outings', 'Health coverage'],
  },
  {
    id: 10,
    title: 'HR Manager',
    location: 'New Delhi, India',
    department: 'People',
    type: 'Full-Time',
    seniority: 'Manager',
    salary: '₹18L - ₹28L',
    postedAt: '2025-09-30',
    description: 'Lead talent programs, employee engagement, and HR operations across India.',
    responsibilities: ['Drive recruitment and onboarding', 'Lead employee engagement initiatives', 'Manage HR operations and policies'],
    requirements: ['5+ years in HR generalist roles', 'Experience running hiring programs at scale'],
    niceToHave: ['Knowledge of local labour laws', 'HRIS experience'],
    perks: ['Competitive benefits', 'Flexible work', 'Learning stipend'],
  },
];

export const HERO_IMG = 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=1600&auto=format&fit=crop&ixlib=rb-4.0.3&s=5a6d9b3b0f9e7f8c8c6a3b6f3a8e9f1a';
